### ISSUE TITLE
RSpecの質問事項

### ISSUE THREAD

**Issue by Toita3n** [Toita3n/expired-foods#29]
現在RSpecでテストコードを書いています。 テストケースを書いてもログインができないので、このような場合のヒントをお願いします。
```
sessions_spec.rb
require 'rails_helper'
require 'factory_bot_rails'

describe 'Sessions', type: :system do
    describe 'ユーザーログインできる' do
      context 'フォームの入力値が正常' do
        it 'ログイン処理が成功する' do
         visit login_path
         user = create(:user)
         login_as(user)
         byebug
         expect(current_path).to eq items_path
         expect(page).to have_content 'ログインしました'
         find(".navbar-toggler-icon").click
         expect(page).to have_content '商品・食材登録'
         expect(page).to have_content 'アカウント設定'
         expect(page).to have_content 'ログアウト'
        end
      end
end

factories/users.rb
FactoryBot.define do
  factory :user do
      name { Faker::Name.last_name }
      email { Faker::Internet.unique.email }
      password { "testpassword" }
      password_confirmation {"testpassword"}
      role {0}
  end
end

support/user_login.rb

module UserLogin
  def login_as(user)
    visit login_path
    fill_in 'メールアドレス', with: user.email
    fill_in 'パスワード', with: user.crypted_password
    find(".btn-login").click
  end
end
```

現在このようなテストコードを書いています。 ログインを試みますが、ログインが失敗してしまします。 このテストコードに対して、byebugを使用したところ
```
spec/system/sessions_spec.rb
    7:         it 'ログイン処理が成功する' do
    8:          visit login_path
    9:          user = create(:user)
   10:          login_as(user)
   11:          byebug
=> 12:          expect(current_path).to eq items_path
   13:          expect(page).to have_content 'ログインしました'
   14:          find(".navbar-toggler-icon").click
   15:          expect(page).to have_content '商品・食材登録'
   16:          expect(page).to have_content 'アカウント設定'
(byebug) user
#<User id: 263, email: "anthony@durgan.example", crypted_password: "$2a$04$q7dmLg35olypPky2EJsmn.agSOc0oUozQVXjuZSQFMv...", salt: "wfp4Dt15ywGEQPk2ysyp", created_at: "2024-01-31 16:27:52.934572000 +0900", updated_at: "2024-01-31 16:27:52.934572000 +0900", reset_password_token: nil, reset_password_token_expires_at: nil, reset_password_email_sent_at: nil, role: "general", name: "小川", uid: nil>
(byebug) user.password
nil
(byebug) user.crypted_password
"$2a$04$q7dmLg35olypPky2EJsmn.agSOc0oUozQVXjuZSQFMv.B/qSL95De"
(byebug) user.email
"anthony@durgan.example"
```
となっているため、emailとcrypted_passwordには情報が入っているようです。となるとfind(".btn-login")が間違っていると思いましたが、       
```
sessions/new.rb
 <div class="button-center">
          <%= f.submit t('defaults.login'), class: 'btn-login' %>
      <% end %>
```
で直接classに対して指定しているので成功していると思われます。 これに関しては、ログインが失敗した場合のテストコードが通っているのでできていると思います。
また、 find(".btn-login").clickようにしている理由として navbar-toggleにログインと表示されているためです。
 以下に現在のsessions_rspec全体を記述します。
```
require 'rails_helper'
require 'factory_bot_rails'

describe 'Sessions', type: :system do
    describe 'ユーザーログインできる' do
      context 'フォームの入力値が正常' do
        it 'ログイン処理が成功する' do
         visit login_path
         user = create(:user)
         login_as(user)
         byebug
         expect(current_path).to eq items_path
         expect(page).to have_content 'ログインしました'
         find(".navbar-toggler-icon").click
         expect(page).to have_content '商品・食材登録'
         expect(page).to have_content 'アカウント設定'
         expect(page).to have_content 'ログアウト'
        end
      end

      context 'フォームが未入力' do
        it 'メールアドレス不足によるログイン処理が失敗する' do
          user = create(:user)
          #ログイン処理
          login_as(user)
          expect(page).to have_content 'ログインに失敗しました'
          expect(current_path).to eq login_path
        end

        it 'パスワード不足によるログイン失敗' do
          user = create(:user)
          login_as(user)
          expect(page).to have_content 'ログインに失敗しました'
          expect(current_path).to eq login_path
        end
      end


      context 'ゲストログイン前' do
        it 'ゲストログインの処理が成功する' do
          visit login_path
          click_link 'ゲストログイン'
          expect(current_path).to eq items_path
          expect(page).to have_content 'ゲストユーザーでログインしました。'
          expect(page).to have_content 'ゲストユーザーは機能を制限しています。'
        end
      end
    end

    describe 'ログイン後' do
      it 'ユーザーのログアウトが成功する' do
         user = create(:user)
         login_as(user)
         expect(page).to have_content 'ログインしました'
         expect(current_path).to eq items_path

         find(".navbar-toggler-icon").click
         click_on 'ログアウト'
         expect(page).to have_content 'ログアウトしますか?'

      end
    end
end
```

長文になりましたが、よろしく精査の程よろしくお願いします。

**Comment by Tsuchiya2** [comment]
エラーのスクリーンショットを確認してみて、どういった状況なのか確認してみましょう。

**Comment by Toita3n** [comment]
お返事ありがとうございます。
自己解決できました。 crypted_passwordで行うと要素を取得できないので,user = create(:user, password: 'testpassword', password_confirmation: 'testpassword')とやって直接入力するようにしました。

**Comment by Toita3n** [comment]
現在, userのprofileのテストコードを書いているのですが、メールアドレスの変更するときに, edit_profile_pathからメールアドレスを編集するようにしています。

![image](https://github.com/Toita3n/expired-foods/assets/119268064/e236f390-7ccf-480d-9e97-f1d346ddd8fa)]
この状態からemailアドレスを入力せずに変更ボタンを押すと以下のようにurlのpathが異なるように見えます。

![image](https://github.com/Toita3n/expired-foods/assets/119268064/7c2bce08-7218-4391-86ba-c2b2dc9081eb)

つまり、最初はhttp://localhost:3000/profile/editとなっているのに変更できないとhttp://localhost:3000/profileに変化しています。これはどのような理由なのでしょうか？
profiles_controllerでは変更できなかった場合はdef update内で render :editとしているので、更新後のpathがprofileなのは少々変だと思います。しかし、再度入力すると、しっかり変更できます。この場合は無視しても問題ないのでしょうか？
```
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :uid)
  end
end
```
```
Started GET "/profile/edit" for ::1 at 2024-02-01 16:30:55 +0900
Processing by ProfilesController#edit as HTML
  User Load (7.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  ↳ app/controllers/application_controller.rb:13:in `current_user'
  CACHE User Load (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  ↳ app/controllers/profiles_controller.rb:20:in `set_user'
  Rendering layout layouts/application.html.erb
  Rendering profiles/edit.html.erb within layouts/application
  Rendered shared/_error_messages.html.erb (Duration: 0.1ms | Allocations: 47)
  Rendered profiles/edit.html.erb within layouts/application (Duration: 1.8ms | Allocations: 863)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered shared/_header.html.erb (Duration: 0.4ms | Allocations: 334)
  Rendered shared/_flash_message.html.erb (Duration: 0.1ms | Allocations: 53)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 244)
  Rendered layout layouts/application.html.erb (Duration: 28.4ms | Allocations: 17326)
Completed 200 OK in 45ms (Views: 29.1ms | ActiveRecord: 7.0ms | Allocations: 19756)


Started PATCH "/profile" for ::1 at 2024-02-01 16:31:02 +0900
Processing by ProfilesController#update as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>""}, "commit"=>"変更"}
  User Load (9.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  ↳ app/controllers/application_controller.rb:13:in `current_user'
  CACHE User Load (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  ↳ app/controllers/profiles_controller.rb:20:in `set_user'
  TRANSACTION (6.9ms)  BEGIN
  ↳ app/controllers/profiles_controller.rb:9:in `update'
  User Exists? (12.7ms)  SELECT 1 AS one FROM `users` WHERE `users`.`name` = 'asakusa' AND `users`.`id` != 1 LIMIT 1
  ↳ app/controllers/profiles_controller.rb:9:in `update'
  User Exists? (8.0ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = '' AND `users`.`id` != 1 LIMIT 1
  ↳ app/controllers/profiles_controller.rb:9:in `update'
  TRANSACTION (5.7ms)  ROLLBACK
  ↳ app/controllers/profiles_controller.rb:9:in `update'
  Rendering layout layouts/application.html.erb
  Rendering profiles/edit.html.erb within layouts/application
  Rendered shared/_error_messages.html.erb (Duration: 0.7ms | Allocations: 355)
  Rendered profiles/edit.html.erb within layouts/application (Duration: 4.1ms | Allocations: 1455)
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered shared/_header.html.erb (Duration: 0.6ms | Allocations: 334)
  Rendered shared/_flash_message.html.erb (Duration: 0.1ms | Allocations: 46)
  Rendered shared/_footer.html.erb (Duration: 0.2ms | Allocations: 244)
  Rendered layout layouts/application.html.erb (Duration: 30.5ms | Allocations: 17823)
Completed 200 OK in 106ms (Views: 32.3ms | ActiveRecord: 42.7ms | Allocations: 26552)
```

**Comment by Tsuchiya2** [comment]
↑画像がコードブロックで表示されていないので、コメント欄に画像が表示される形にしていただけますか。
一旦お返しします。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
確認できました。

> 最初は[http://localhost:3000/profile/editとなっているのに変更できないとhttp://localhost:3000/profileに変化しています。これはどのような理由なのでしょうか？

```
bin/rails routes
```

↑のコマンドで対象のコントローラー#アクションが動く際のURIパターン・HTTPメソッドを確認してみてください。なぜ.../editにならないのかRailsガイドなどを参照して復習しましょう。

> profiles_controllerでは変更できなかった場合はdef update内で render :editとしているので、更新後のpathがprofileなのは少々変だと思います。しかし、再度入力すると、しっかり変更できます。この場合は無視しても問題ないのでしょうか？

こちらも同様ですね。Railsで理解できていない部分かと思うので復習しましょう。

https://railsguides.jp/routing.html

**Comment by Toita3n** [comment]
しっかり renderとredirect_to の違いを再復習しました。ありがとうございました.
